# Generated by Django 4.0.3 on 2022-03-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
